# Generated by Django 6.0 on 2026-01-01 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("course", models.CharField(db_index=True, max_length=255)),
                ("duration_minutes", models.PositiveIntegerField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MCQ", "Multiple Choice"),
                            ("SHORT", "Short Answer"),
                            ("ESSAY", "Essay"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("prompt", models.TextField()),
                ("expected_answer", models.TextField(blank=True, default="")),
                ("options", models.JSONField(blank=True, default=list)),
                ("max_score", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assessments.exam",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["exam", "question_type"],
                        name="assessments_exam_id_4fbae3_idx",
                    )
                ],
            },
        ),
    ]
